INSERT INTO "PriceItem" (
  "id",
  "category",
  "label",
  "description",
  "unit",
  "price",
  "min",
  "max",
  "priceText",
  "mainCategory",
  "active"
) VALUES
  (
    'price-porto-verpackung-deutschland',
    'Versandkosten',
    'Porto/Verpackung Deutschland',
    'Klein-Paket / Rueckversand innerhalb Deutschlands',
    NULL,
    NULL,
    NULL,
    NULL,
    '6,95 EUR',
    'Versand',
    TRUE
  ),
  (
    'price-porto-verpackung-eu-versandzone-1',
    'Versandkosten',
    'Porto/Verpackung EU Versandzone 1',
    'Klein-Paket in EU-Laender, Versandzone 1',
    NULL,
    NULL,
    NULL,
    NULL,
    '18 EUR | versandkostenfrei ab 150 EUR Warenwert',
    'Versand',
    TRUE
  ),
  (
    'price-porto-verpackung-europa-nicht-eu-versandzone-2',
    'Versandkosten',
    'Porto/Verpackung Europa Nicht-EU Versandzone 2',
    'Klein-Paket in Europa Nicht-EU, z. B. Schweiz, Norwegen, UK, Liechtenstein',
    NULL,
    NULL,
    NULL,
    NULL,
    '38 EUR | versandkostenfrei ab 150 EUR Warenwert',
    'Versand',
    TRUE
  ),
  (
    'price-porto-verpackung-weltweit-versandzone-3',
    'Versandkosten',
    'Porto/Verpackung Weltweit Versandzone 3',
    'Klein-Paket weltweit, z. B. USA, Kanada, Australien',
    NULL,
    NULL,
    NULL,
    NULL,
    '48 EUR | keine Freigrenze hinterlegt',
    'Versand',
    TRUE
  ),
  (
    'price-gitarrenversand-deutschland',
    'Gitarrenversand',
    'Gitarrenversand Deutschland',
    'Gitarrenversand innerhalb Deutschlands bis 25.000 EUR Versicherungswert',
    NULL,
    NULL,
    NULL,
    NULL,
    'kostenlos bis 25.000 EUR Versicherungswert',
    'Versand',
    TRUE
  ),
  (
    'price-gitarrenversand-eu-versandzone-1',
    'Gitarrenversand',
    'Gitarrenversand EU Versandzone 1',
    'Gitarrenversand in EU-Laender, Versandzone 1, bis 3.000 EUR Versicherungswert',
    NULL,
    NULL,
    NULL,
    NULL,
    '60 EUR bis 3.000 EUR Versicherungswert',
    'Versand',
    TRUE
  ),
  (
    'price-gitarrenversand-europa-nicht-eu-versandzone-2',
    'Gitarrenversand',
    'Gitarrenversand Europa Nicht-EU Versandzone 2',
    'Gitarrenversand in Europa Nicht-EU, z. B. Schweiz, Norwegen, UK, Liechtenstein, bis 3.000 EUR Versicherungswert',
    NULL,
    NULL,
    NULL,
    NULL,
    '79 EUR bis 3.000 EUR Versicherungswert',
    'Versand',
    TRUE
  ),
  (
    'price-gitarrenversand-weltweit-versandzone-3',
    'Gitarrenversand',
    'Gitarrenversand Weltweit Versandzone 3',
    'Gitarrenversand weltweit, z. B. USA, Kanada, Australien, bis 3.000 EUR Versicherungswert',
    NULL,
    NULL,
    NULL,
    NULL,
    '106 EUR bis 3.000 EUR Versicherungswert',
    'Versand',
    TRUE
  ),
  (
    'price-versandmarke-einsendung-deutschland',
    'Versandmarke',
    'Versandmarke Einsendung Deutschland',
    'Service fuer die Einsendung einer Vorlage innerhalb Deutschlands; Adresse des Kunden erforderlich',
    NULL,
    NULL,
    NULL,
    NULL,
    'ab 69 EUR Auftragswert moeglich',
    'Versand',
    TRUE
  )
ON CONFLICT ("id") DO UPDATE SET
  "category" = EXCLUDED."category",
  "label" = EXCLUDED."label",
  "description" = EXCLUDED."description",
  "unit" = EXCLUDED."unit",
  "price" = EXCLUDED."price",
  "min" = EXCLUDED."min",
  "max" = EXCLUDED."max",
  "priceText" = EXCLUDED."priceText",
  "mainCategory" = EXCLUDED."mainCategory",
  "active" = EXCLUDED."active";
